### ISSUE TITLE
e621updater.exe missing from e621_updater-v9.6

### ISSUE THREAD

**Issue by Dividedby0KSJ** [AyoKeito/e621updater#7]
why does `e621updaterv9p6.zip` not contain the same content as `updaterv9p5.zip`
Missing files being. `curl.exe` `e621updater.exe` `exiftool.exe`

I can understand `curl.exe` & `exiftool.exe` as they are not made by you, but the primary program `e621updater.exe` is not in the current release.

this is not an attack or anything, I realised typing this that the tone may seem angry or something, but it's a genuine question that I can learn from, as I am getting into developing programs myself.

Is there a legal / ToS reason? or just a mistake?

**Comment by AyoKeito** [comment]
Hey!
Better late than never, i guess. It seems that my notifications were disabled.

> I can understand curl.exe & exiftool.exe as they are not made by you

Yeah, i don't know if i can include them, so i decided not to.

>but the primary program e621updater.exe is not in the current release.

That's a mistake, because the fixed code wasn't written by me, so i've just pushed all the changes quickly and didn't check what i'm doing.
